const condition = {
  WIND: "wind",
  THUNDERSTORM: "thunderstorm",
  RAIN: "rain",
  SNOW: "snow",
  CLOUDY: "cloudy",
  MIXED: "mixed",
  SUNNY: "sunny"
}

// reference: https://openweathermap.org/weather-conditions#Weather-Condition-Codes-2
condition.fromCode = function fromCode(code) {
  return {
    200: condition.THUNDERSTORM,
    201: condition.THUNDERSTORM,
    202: condition.THUNDERSTORM,
    210: condition.THUNDERSTORM,
    211: condition.THUNDERSTORM,
    212: condition.THUNDERSTORM,
    221: condition.THUNDERSTORM,
    230: condition.THUNDERSTORM,
    231: condition.THUNDERSTORM,
    232: condition.THUNDERSTORM,
    300: condition.RAIN,
    301: condition.RAIN,
    302: condition.RAIN,
    310: condition.RAIN,
    311: condition.RAIN,
    312: condition.RAIN,
    313: condition.RAIN,
    314: condition.RAIN,
    321: condition.RAIN,
    500: condition.RAIN,
    501: condition.RAIN,
    502: condition.RAIN,
    503: condition.RAIN,
    504: condition.RAIN,
    511: condition.SNOW,
    520: condition.RAIN,
    521: condition.RAIN,
    522: condition.RAIN,
    531: condition.RAIN,
    600: condition.SNOW,
    601: condition.SNOW,
    602: condition.SNOW,
    611: condition.SNOW,
    612: condition.SNOW,
    613: condition.SNOW,
    615: condition.SNOW,
    616: condition.SNOW,
    620: condition.SNOW,
    621: condition.RAIN,
    622: condition.RAIN,
    701: condition.CLOUDY,
    711: condition.CLOUDY,
    721: condition.CLOUDY,
    731: condition.WIND,
    741: condition.CLOUDY,
    751: condition.CLOUDY,
    761: condition.CLOUDY,
    762: condition.CLOUDY,
    771: condition.WIND,
    781: condition.WIND,
    800: condition.SUNNY,
    801: condition.MIXED,
    802: condition.CLOUDY,
    803: condition.CLOUDY,
    804: condition.CLOUDY
  }[code]
}

module.exports = condition
