const condition = {
  WIND: "wind",
  THUNDERSTORM: "thunderstorm",
  RAIN: "rain",
  SNOW: "snow",
  CLOUDY: "cloudy",
  MIXED: "mixed",
  SUNNY: "sunny"
}


condition.fromCode = function fromCode(code) {
  return {
    0: condition.WIND,
    1: condition.WIND,
    2: condition.WIND,
    3: condition.THUNDERSTORM,
    4: condition.THUNDERSTORM,
    5: condition.RAIN,
    6: condition.RAIN,
    7: condition.SNOW,
    8: condition.RAIN,
    9: condition.RAIN,
    10: condition.RAIN,
    11: condition.RAIN,
    12: condition.RAIN,
    13: condition.SNOW,
    14: condition.SNOW,
    15: condition.SNOW,
    16: condition.SNOW,
    17: condition.RAIN,
    18: condition.RAIN,
    19: condition.CLOUDY,
    20: condition.CLOUDY,
    21: condition.CLOUDY,
    22: condition.CLOUDY,
    23: condition.WIND,
    24: condition.WIND,
    25: condition.SNOW,
    26: condition.CLOUDY,
    27: condition.CLOUDY,
    28: condition.CLOUDY,
    29: condition.MIXED,
    30: condition.MIXED,
    31: condition.SUNNY,
    32: condition.SUNNY,
    33: condition.MIXED,
    34: condition.MIXED,
    35: condition.RAIN,
    36: condition.SUNNY,
    37: condition.THUNDERSTORM,
    38: condition.THUNDERSTORM,
    39: condition.THUNDERSTORM,
    40: condition.RAIN,
    41: condition.SNOW,
    42: condition.SNOW,
    43: condition.SNOW,
    44: condition.MIXED,
    45: condition.THUNDERSTORM,
    46: condition.SNOW,
    47: condition.THUNDERSTORM
  }[code]
}

module.exports = condition
